//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppLuxoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public int id { get; set; }
        public string name { get; set; }
        public string fullName { get; set; }
        public string address { get; set; }
        public string emailid { get; set; }
        public System.DateTime dob { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<bool> deactivaed { get; set; }
    }
}
